In [1]:
#Que1
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [2]:
#Yes, there is a difference in the data type of variables list_ and array_list. list___ is a Python list object, while __array_list is a NumPy array object.

In [3]:
type(list_)

list

In [4]:
type(array_list)

numpy.ndarray

In [5]:
#Que2
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

In [6]:
# Each element is string class
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [7]:
# Each element is numpy_string class
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [8]:
#Que3
#array_list = np.array(object = list_, dtype = int)

In [9]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object = list_, dtype = int)

In [10]:
# Each element is string class
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [11]:
# Each element is numpy_integer class
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [12]:
'''The first loop will print the data type of each element in list_, which will be <class 'str'>, since all the elements in list_ are strings.

The second loop will print the data type of each element in array_list, which will be <class 'numpy.int64'>, since all the elements in array_list are now integers due to the dtype=int parameter passed to the np.array() function.'''

"The first loop will print the data type of each element in list_, which will be <class 'str'>, since all the elements in list_ are strings.\n\nThe second loop will print the data type of each element in array_list, which will be <class 'numpy.int64'>, since all the elements in array_list are now integers due to the dtype=int parameter passed to the np.array() function."

In [13]:
#Que4
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [14]:
#(i) shape of num_array
#The shape attribute of a numpy array returns a tuple containing the dimensions of the array.

num_array.shape

(2, 3)

In [15]:
#(ii) size of num_array
#The size attribute of a NumPy array returns the total number of elements in the array.

num_array.size

6

In [16]:
#Que5
a=np.zeros((3,3))

In [17]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.array([[0,0,0],[0,0,0],[0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
a.shape

(3, 3)

In [20]:
a.size

9

In [21]:
#Que6
a=np.eye(5,5)

In [22]:
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [23]:
a.shape

(5, 5)

In [24]:
a.size

25